export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';

export const CHANGE_GAME_INFO = 'CHANGE_GAME_INFO';

export const START_TIMER = 'START_TIMER';
export const INCREMENT_TIME = 'INCREMENT_TIME';
export const STOP_TIMER = 'STOP_TIMER';
export const SET_CARDS = 'SET_CARDS';
export const SET_GAME_ENDED = 'SET_GAME_ENDED';

export const ADD_CARD_TO_SELECTED_CARDS = 'ADD_CARD_TO_SELECTED_CARDS';
export const RESET_SELECTED_CARDS = 'RESET_SELECTED_CARDS';
export const RESET_MATCHED_CARDS = 'RESET_MATCHED_CARDS';
export const ADD_CARDS_TO_MATCHED_CARDS = 'ADD_CARDS_TO_MATCHED_CARDS';

export const SET_TOP_STATS = 'SET_TOP_STATS';
export const SET_TOP_STATS_LOADING = 'SET_TOP_STATS_LOADING';
